services:
  cyclone_openviking:
    image: 10.86.20.10/library/cyclone-openviking:test
    container_name: cyclone-openviking
    ports:
      - "1933:1933"
    volumes:
      - ./data:/app/.openviking
    environment:
      OPENVIKING_CONF_CONTENT: ${OPENVIKING_CONF_CONTENT:-}
    restart: unless-stopped